_profile_path: ''
_log_level: 0
client_db:
  db_loc: ./worker-clients.db
  db_standard: sqlite:///
manager:
  addr: 127.0.0.1
  port: '4000'
  interval: 2
addr: 127.00.0.1
port: '4001'
root_dir: ./_worker
